### PR TITLE
ReWork groups

### PR DESCRIPTION
**Pull request by vmorganp**

### CODE REVIEW

**Comment by vmorganp** [comment]
Hey Lazytainer contributors! I've been working on some changes to address a common complaint I see, which is that you have to run one Lazytainer instance for every service you want to stop. This change should address that and since you folks are contributors already I figured I'd ask for some help and feedback.

@JackBailey any chance you can update the zerotier example to work with this?
I'm unfamiliar with zerotier and don't have the knowledge to test it, but I'd be happy to work with you on getting it updated to  lazytainer v2.

@pratikbin apologies, I know I undid a lot of the work you did on the Dockerfile with this. I'm not sure that this set of changes works with a scratch image, since the pcap dependency exists now. If you know of a way to make that happen I can look at it, or as usual you're than welcome to update it again. 

 @calrock27 I know I haven't looked at your PR since the comment, that was largely because I was working on this. Do you want to update your PR to work with this or do you want me to create a request to your request (*inception noise*)?

**Comment by JackBailey** [comment]
I don't currently really have any free time to work on the example unfortunately but all it needs is to take in the listening interface as an env variable so just replace the lazytainer part of the compose file with the new v2 config (however you've done it) and set the interface variable to ztukuxxqii

**Comment by pratikbin** [comment]
Will take a look at it ser

**Comment by vmorganp** [comment]
Hey @pratikbin I'm planning on releasing on the first of February. I'm not sure if you've had a chance to look around, but if you want to make changes, let me know before then please.

**Comment by pratikbin** [comment]
> Hey @pratikbin I'm planning on releasing on the first of February. I'm not sure if you've had a chance to look around, but if you want to make changes, let me know before then please.

Haven't gotten chance to look at it again. I don't think will gate time before fab. Can go ahead for now ser

**Comment by calrock27** [comment]
No inception noise needed :) I'll update mine. Apologies for the delay

**Comment by vmorganp** [comment]
> No inception noise needed :) I'll update mine. Apologies for the delay

No worries, thanks in advance for your contribution!

**Pull request merged**
