### PR TITLE
Add interface environment variable

### PR DESCRIPTION
**Pull request by Jack-Bailey**

### CODE REVIEW

**Comment by Jack-Bailey** [comment]
Haven't touched Go before but seems to work in my testing - Please check though.

My usecase: Using it with dockerized zerotier to allow minecraft with lazytainer to work through zerotier.

**Comment by vmorganp** [comment]
I don't actually run tailscale but I'm going to approve on the grounds that more configurability is more better especially when it's non-breaking. I'm also taking your word for it on this working with tailscale.

**Review by vmorganp — APPROVED** [review]

**Comment by Jack-Bailey** [comment]
> I don't actually run tailscale but I'm going to approve on the grounds that more configurability is more better especially when it's non-breaking.

I'm using it with zerotier personally - not sure if a docker tailscale version exists. 


> I'm also taking your word for it on this working with tailscale.

Yep - I've been using my fork of this with zerotier for the last few days without any problems after I got my depends_on right - I'll probably create a guide on this soon

**Comment by vmorganp** [comment]
Do you have the ability to merge?
If so, feel free to do so

**Comment by Jack-Bailey** [comment]
I don't no - I'll just add it to this PR

**Comment by Jack-Bailey** [comment]
Done

**Comment by vmorganp** [comment]
I created a PR into your fork for a couple of formatting things. https://github.com/Jack-Bailey/Lazytainer/pull/1

**Comment by Jack-Bailey** [comment]
Merged

**Pull request merged**
